version: 2

builds:
  - id: wrc-laptimer
    dir: cmd/wrc-laptimer
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    # hooks:
    #   pre: task web:build

archives:
  - id: wrc-laptimer
    ids: [wrc-laptimer]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
