version: 2

builds:
  - id: wrc-laptimer
    dir: cmd/wrc-laptimer
    env:
      - CGO_ENABLED=1
    goos:
      - ""
    goarch:
      - ""
    # hooks:
    #   pre: task web:build

archives:
  - id: wrc-laptimer
    ids: [wrc-laptimer]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-checksum.txt"
