name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: [lint, test]
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go

  publish:
    name: Publish artifacts
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pcscd libpcsclite1 libpcsclite-dev g++-13

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          choco install yq

      - name: Modify goreleaser config
        shell: bash
        run: yq --inplace ".builds[0].goos[0] = \"$(go env GOOS)\" | .builds[0].goarch[0] = \"$(go env GOARCH)\"" .goreleaser.yaml

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Pass any additional environment variables needed for your build

  post-publish:
    name: Post-publish tasks
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        name: Update release label on PR
        with:
          script: |
            const { data: { items } } = await github.rest.search.issuesAndPullRequests({
              q: `${context.sha} type:pr is:merged`
            });

            const issue = {
              issue_number: items[0].number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            };

            github.rest.issues.addLabels({
              ...issue,
              labels: ["autorelease: published"],
            });

            github.rest.issues.removeLabel({
              ...issue,
              name: "autorelease: tagged",
            });
